### ISSUE TITLE
variable local 'loop' referenced before assignment 

### ISSUE THREAD

**Issue by ezratoga** [muchlisinadi/ALPR-Indonesia#8]
![image_2020-11-10_140846](https://user-images.githubusercontent.com/67219628/98641387-3fd8c180-235e-11eb-8f62-9afa10d99f3b.png)

excuse me, i wan to ask something. why the output when i want to test your code are like this? thx before

mengapa error di variable loop dan saat menjalankan fungsi main()?

**Comment by muchlisinadi** [comment]
please re-pull the code, I made some updates
